### ISSUE TITLE
"force" parameter explicitly need to be set

### ISSUE THREAD

**Issue by nervo** [gantsign/alt-galaxy#30]
According to this: https://github.com/gantsign/alt-galaxy/blob/3b1221fc58ce4697aeaa4d58381042174b6ab214/main.go#L57

Not a big deal, but i just wonder why you can't support the "no force" mode.

**Comment by freemanjp** [comment]
My particular use case for this tool is to provision a virtual machine for developer use; I always want to use the role versions specified in my `requirements.yml`; indeed Vagrant defaults to using `--force` when running `ansible-galaxy` (https://www.vagrantup.com/docs/provisioning/ansible_common.html#galaxy_command); without `--force` it will not update roles that are already installed. There's also the fact that `alt-galaxy` is so fast there's little to gain by only downloading new roles.

Without `--force` `ansible-galaxy` will skip the role install if `meta/.galaxy_install_info` is present (https://github.com/ansible/ansible/blob/v2.2.0.0-1/lib/ansible/cli/galaxy.py#L391) and error if the role directory is present without the `meta/.galaxy_install_info` (https://github.com/ansible/ansible/blob/v2.2.0.0-1/lib/ansible/galaxy/role.py#L274); it seems `ansible-galaxy` ignores the version in `.galaxy_install_info`; I assume `ansible-galaxy` is using `.galaxy_install_info` as a check to see if the role was installed successfully (since it's written after untaring the role).

So making `--force` optional will require:

1. Writing the `meta/.galaxy_install_info` after untaring the role
2. A conditional to avoid re-downloading the role if `meta/.galaxy_install_info` is present
3. A conditional to error if role is present without `meta/.galaxy_install_info`
4. Minor changes to the CLI

Of course writing the `meta/.galaxy_install_info` would have the additional benefit of enabling `ansible-galaxy` to list the installed roles.

Given it's a feature I'm not likely to use, I'm not going to implement it myself, but I'd be happy to review/merge a pull request if you want to implement it.

**Comment by nervo** [comment]
Ok, challenge not accepted at all :)

Backporting "meta/.galaxy_install_info" handling is far too risky, and i have found a better approach.

But first, a little bit of background. We (will soon) use alt-galaxy in our development environment process:
-  a debian package https://github.com/manala/debian-package-alt-galaxy
- an ansible-galaxy role https://github.com/manala/ansible-role-ansible-galaxy with alternative capabilities (aka. using alt-galaxy if detected)

In this specific ansible role, we can force the "force" parameter if alt-galaxy is detected (https://github.com/manala/ansible-role-ansible-galaxy/blob/master/tasks/alternatives.yml#L13)

This way, everybody is happy :)

**Comment by freemanjp** [comment]
Fair enough.

Frankly, I'm a little surprised that anyone found `alt-galaxy`, let alone has created a Debian package for it and will be using it in their development environment process.

Just out of interest, are you using it because it suffers less from intermittent HTTP issues or because it's faster than `ansible-galaxy`?

**Comment by nervo** [comment]
I don't remember exactly how nor when we found it :)
We're a medium size web developpment company, spending a lot of time to create/destroy virtual machines for our projects. Alt galaxy makes us winning around 10 minutes per cycle !
And yes, we're winning this time, because ansible-galaxy is a little piece of s**t, slow as hell, with some http issues.

Once again, thank you :)
